name: gdutils

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up GoLang
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Run unit tests
        run: go test -race -coverprofile=c.out ./...